catalog:
  '@commitlint/cli': 20.2.0
  '@commitlint/config-conventional': 20.2.0
  '@biomejs/biome': 2.3.10
  lefthook: 2.0.13
  remark: 15.0.1
  remark-cli: 12.0.1
  remark-frontmatter: 5.0.0
  remark-gfm: 4.0.1
  remark-lint: 10.0.1
  remark-preset-lint-consistent: 6.0.1
  remark-preset-lint-recommended: 7.0.1
  remark-toc: 9.0.0
  textlint: 15.5.0
  textlint-filter-rule-allowlist: 4.0.0
  textlint-filter-rule-comments: 1.2.2
  textlint-rule-preset-ja-technical-writing: 12.0.2

catalogMode: strict

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

engineStrict: true

linkWorkspacePackages: true

nodeVersion: 24.11.0

onlyBuiltDependencies:
  - lefthook

preferWorkspacePackages: true

saveWorkspaceProtocol: true

shamefullyHoist: false

sharedWorkspaceLockfile: true

strictPeerDependencies: true
