name: 機能リクエスト
description: 既存プラグインへの機能追加や改善を提案する
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        機能リクエストありがとうございます。
        具体的なユースケースを記載していただけると、検討がスムーズになります。

  - type: textarea
    id: summary
    attributes:
      label: 機能の概要
      description: どのような機能を追加・改善してほしいですか？
      placeholder: 例：diagram-drawio で Mermaid 形式の出力に対応してほしい
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: ユースケース
      description: この機能がどのような場面で役立つか説明してください
      placeholder: 例：Mermaid 形式で出力できれば、GitHub の README に直接埋め込める
    validations:
      required: true

  - type: dropdown
    id: plugin
    attributes:
      label: 対象プラグイン
      description: 機能を追加したいプラグインを選択してください
      options:
        - diagram-drawio
        - 全体（新機能）
        - その他
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 現在この問題をどのように解決していますか？他の解決策はありますか？
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 追加情報
      description: その他、参考になる情報があれば記載してください
    validations:
      required: false
